### ISSUE TITLE
flet -v 2.21.2

### ISSUE THREAD

**Issue by jundaychan** [Daxexs/flet-easy#10]
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\junda\AppData\Local\Temp\serious_python_tempfc4da465\main.py", line 2, in <module>
  File "C:\Users\junda\AppData\Local\Temp\serious_python_tempfc4da465\__pypackages__\flet_easy\__init__.py", line 1, in <module>
  File "C:\Users\junda\AppData\Local\Temp\serious_python_tempfc4da465\__pypackages__\flet_easy\fletEasy.py", line 8, in <module>
  File "C:\Users\junda\AppData\Local\Temp\serious_python_tempfc4da465\__pypackages__\flet_easy\inheritance.py", line 579, in <module>
  File "C:\Users\junda\AppData\Local\Temp\serious_python_tempfc4da465\__pypackages__\flet_easy\inheritance.py", line 589, in Viewsy
  File "D:\code\auto_jianying\baolaapp\Lib\enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: NONE

打包失败

**Comment by jundaychan** [comment]
0.22.0

**Comment by jundaychan** [comment]
mabey is flet problem

**Comment by Daxexs** [comment]
Try this version:  https://pypi.org/project/flet-easy/0.2.0.dev7/

**Comment by jundaychan** [comment]
> Try this version: https://pypi.org/project/flet-easy/0.2.0.dev7/
I downgraded the flet version and it worked, I'll try this later on

**Comment by NocoleNe** [comment]
It's great,
with flet 0.22.0, can control run way from code like this
`ft.app(target=main, view=ft.AppView.WEB_BROWSER)`
how  to do  in Flet-Easy？

**Comment by Daxexs** [comment]
> Es genial, con flet 0.22.0, puedes controlar la ejecución desde un código como este, `ft.app(target=main, view=ft.AppView.WEB_BROWSER)` ¿cómo se hace en Flet-Easy?

Yes, just use the `run()` method of the `FletEasy` class
