### ISSUE TITLE
Exception: Timeout waiting for invokeMethod clientStorage:get({'key': 'USERNAME'}) call

### ISSUE THREAD

**Issue by NooRMaseR** [Daxexs/flet-easy#19]
**Exception: Timeout waiting for invokeMethod clientStorage:get({'key': 'USERNAME'}) call**

hi, i have an issue here since i have updated to the latest version and when i run the app i get this error when using this code `page.client_storage.get()` like this simple code

```python
class ChatUI(ft.SafeArea):
    
    def __init__(self, window: ft.Page) -> None:
        super().__init__()
        self.window: ft.Page = window
	self.username: str = (
            "User"
            if not self.window.client_storage.get("USERNAME") 
            else self.window.client_storage.get("USERNAME") 
        )
```

and here's the `main.py` file
```python
from pages.Chat import ChatUI
import flet_easy as fs
import flet as ft


app = fs.FletEasy(route_init="/chat")

@app.config
def app_config(data: ft.Page):
    page = data.page
    THEME: str | None = page.client_storage.get("THEME") # type: ignore
    if THEME:
        page.theme_mode = THEME # type: ignore
    else:
        THEME = "system"
        page.client_storage.set("THEME", THEME) # type: ignore
        page.theme_mode = THEME # type: ignore

        
@app.page("/chat", protected_route=True, share_data=True)
def main(data: fs.Datasy) -> ft.View:
    page = data.page
    page.title = "MaseR Assistant"

    UI = ChatUI(page)
    return ft.View("/chat", controls=[UI])

app.run(assets_dir="assets")

```

and i get this error

```
exception calling callback for <Future at 0x24260cf2630 state=finished raised AttributeError>
Traceback (most recent call last):
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 519, in _on_completion
    raise exception
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_easy\route.py", line 103, in __add_configuration_start
    self.__view_config(self.__page)
  File "D:\backup\programming\Python\MaseR Assistant 2\main app\main.py", line 13, in app_config
    THEME: str | None = page.client_storage.get("THEME") # type: ignore
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'client_storage'
self.data_client = <flet_easy.inheritance.SessionStorageEdit object at 0x0000024260CF25A0>
exception calling callback for <Future at 0x24260a90f80 state=finished raised TimeoutError>
Traceback (most recent call last):
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks 
    callback(self)
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 519, in _on_completion
    raise exception
TimeoutError: Timeout waiting for invokeMethod clientStorage:get({'key': 'USERNAME'}) call
Unhandled error processing page session : Traceback (most recent call last):
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_easy\route.py", line 261, in _go
    self.__page.run_task(self._view_append, route).result()
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks       
    callback(self)
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 519, in _on_completion      
    raise exception
TimeoutError: Timeout waiting for invokeMethod clientStorage:get({'key': 'USERNAME'}) call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_runtime\app.py", line 242, in on_session_created
    await asyncio.get_running_loop().run_in_executor(
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_easy\fletEasy.py", line 175, in main
    app.run()
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_easy\route.py", line 142, in run
    self._go(self.__page.route)
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_easy\route.py", line 273, in _go
    raise Exception(e)
Exception: Timeout waiting for invokeMethod clientStorage:get({'key': 'USERNAME'}) call
```

**Comment by Daxexs** [comment]
Review the documentation please: https://daxexs.github.io/flet-easy/latest/Customized-app/General-settings/

* The error happens that the function decorated by `config` receives `page` as a parameter and not `data`
* Recommend using `async` methods when using `client_storage`, if such errors occur.
* That error is on Flet's part. [more information](https://github.com/flet-dev/flet/issues/2948)

**Example:**
```python
import flet_easy as fs
import flet as ft

class ChatUI(ft.SafeArea):
    def __init__(self, window: ft.Page) -> None:
        super().__init__()
        self.window: ft.Page = window
        self.username: str = window.run_task(self.username_result).result()

    async def username_result(self):
        return (
            "User"
            if not await self.window.client_storage.get_async("USERNAME")
            else await self.window.client_storage.get_async("USERNAME")
        )

app = fs.FletEasy(route_init="/chat")

@app.config
async def app_config(page: ft.Page):
    THEME: str | None = await page.client_storage.get_async("THEME")  # type: ignore
    if THEME:
        page.theme_mode = THEME  # type: ignore
    else:
        THEME = "system"
        await page.client_storage.set_async("THEME", THEME)  # type: ignore
        page.theme_mode = THEME  # type: ignore

@app.page("/chat", share_data=True)
def main(data: fs.Datasy) -> ft.View:
    page = data.page
    page.title = "MaseR Assistant"

    UI = ChatUI(page)
    return ft.View("/chat", controls=[UI])

app.run(assets_dir="assets")
```

**Comment by NooRMaseR** [comment]
> Review the documentation please: https://daxexs.github.io/flet-easy/latest/Customized-app/General-settings/
> 
> * The error happens that the function decorated by `config` receives `page` as a parameter and not `data`
> * Recommend using `async` methods when using `client_storage`, if such errors occur.
> * That error is on Flet's part. [more information](https://github.com/flet-dev/flet/issues/2948)
> 
> **Example:**
> 
> ```python
> import flet_easy as fs
> import flet as ft
> 
> class ChatUI(ft.SafeArea):
>     def __init__(self, window: ft.Page) -> None:
>         super().__init__()
>         self.window: ft.Page = window
>         self.username: str = window.run_task(self.username_result).result()
> 
>     async def username_result(self):
>         return (
>             "User"
>             if not await self.window.client_storage.get_async("USERNAME")
>             else await self.window.client_storage.get_async("USERNAME")
>         )
> 
> app = fs.FletEasy(route_init="/chat")
> 
> @app.config
> async def app_config(page: ft.Page):
>     THEME: str | None = await page.client_storage.get_async("THEME")  # type: ignore
>     if THEME:
>         page.theme_mode = THEME  # type: ignore
>     else:
>         THEME = "system"
>         await page.client_storage.set_async("THEME", THEME)  # type: ignore
>         page.theme_mode = THEME  # type: ignore
> 
> @app.page("/chat", share_data=True)
> def main(data: fs.Datasy) -> ft.View:
>     page = data.page
>     page.title = "MaseR Assistant"
> 
>     UI = ChatUI(page)
>     return ft.View("/chat", controls=[UI])
> 
> app.run(assets_dir="assets")
> ```

sorry but now the app is stuck at this line of code
```python
self.username = self.window.run_task(self.username_result).result()
```

and i added  `print` below it to see the result and i get nothing, it's stuck, here's the code
```python
class ChatUI(ft.SafeArea):
    "The Main UI for Chat Route"
    def __init__(self, window: ft.Page) -> None:
        super().__init__()
        self.window: ft.Page = window
        self.username = self.window.run_task(self.username_result).result()
        print(self.username) #this line of code is not working because the code before it did not finish yet and i waited for 15 minutes and nothing happend
        self.theme: str = self.window.run_task(self.theme_result).result()

    async def username_result(self) -> str | None:
        return (
            "User"
            if not await self.window.client_storage.get_async("USERNAME")
            else await self.window.client_storage.get_async("USERNAME")
        )

    async def theme_result(self) -> str | None:
        return (
            "User"
            if not await self.window.client_storage.get_async("THEME")
            else await self.window.client_storage.get_async("THEME")
        )

```

**Comment by Daxexs** [comment]
For now you can use it like this, since I just found a bug, I will fix it soon.
* The solution will allow using `client_storage.get` without causing the error mentioned above.

```python
class ChatUI(ft.SafeArea):
    "The Main UI for Chat Route"
    def __init__(self, window: ft.Page) -> None:
        super().__init__()
        self.window: ft.Page = window
        self.username = self.window.run_task(self.username_result)
        print(self.username) #this line of code is not working because the code before it did not finish yet and i waited for 15 minutes and nothing happend
        self.theme: str = self.window.run_task(self.theme_result)

    async def username_result(self) -> str | None:
        self.username = (
            "User"
            if not await self.window.client_storage.get_async("USERNAME")
            else await self.window.client_storage.get_async("USERNAME")
        )

    async def theme_result(self) -> str | None:
        self.theme = (
            "system"
            if not await self.window.client_storage.get_async("THEME")
            else await self.window.client_storage.get_async("THEME")
        )

```

**Comment by NooRMaseR** [comment]
> For now you can use it like this, since I just found a bug, I will fix it soon.
> * The solution will allow using `client_storage.get` without causing the error mentioned above.
> 
> ```python
> class ChatUI(ft.SafeArea):
>     "The Main UI for Chat Route"
>     def __init__(self, window: ft.Page) -> None:
>         super().__init__()
>         self.window: ft.Page = window
>         self.username = self.window.run_task(self.username_result)
>         print(self.username) #this line of code is not working because the code before it did not finish yet and i waited for 15 minutes and nothing happend
>         self.theme: str = self.window.run_task(self.theme_result)
> 
>     async def username_result(self) -> str | None:
>         self.username = (
>             "User"
>             if not await self.window.client_storage.get_async("USERNAME")
>             else await self.window.client_storage.get_async("USERNAME")
>         )
> 
>     async def theme_result(self) -> str | None:
>         self.theme = (
>             "system"
>             if not await self.window.client_storage.get_async("THEME")
>             else await self.window.client_storage.get_async("THEME")
>         )
> 
> ```

Yes please, thank you, i would really appreciate it 🙏🏻

**Comment by NooRMaseR** [comment]
thank you for solving the problem
