### ISSUE TITLE
TypeError: app() got an unexpected keyword argument 'auth_token'

### ISSUE THREAD

**Issue by NooRMaseR** [Daxexs/flet-easy#3]
hi i have just updated `flet-easy` and when i try to run my app i get this error
i'm using windows 10

```
C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_models.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  import cgi
C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\speech_recognition\__init__.py:11: DeprecationWarning: 'aifc' is deprecated and slated for removal in Python 3.13
  import aifc
C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\speech_recognition\__init__.py:13: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
  import audioop
C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\pkgdata.py:25: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import resource_stream, resource_exists
C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py:2846: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
pygame 2.5.2 (SDL 2.28.3, Python 3.12.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "D:\backup\programming\Python\MaseR Assistant 2\main app\main.py", line 48, in <module>
    app.run(assets_dir="assets")
  File "C:\Users\workstation\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_easy\fletEasy.py", line 183, in run
    app(
TypeError: app() got an unexpected keyword argument 'auth_token'
```

**Comment by Daxexs** [comment]
Thanks for your report I will take it into account in the next version of `flet-easy 0.2.0`, to be fully compatible with the `flet 0.21.1` version. For the moment I will make a pre-release version fixing this bug.

**Comment by Daxexs** [comment]
Provide me your code as an example of what generates the error please.

**Comment by Daxexs** [comment]
Upgrade [Flet-Easy](https://github.com/Daxexs/flet-easy/releases/tag/0.1.3).

**Comment by NooRMaseR** [comment]
> Provide me your code as an example of what generates the error please.

Yeh sure

```python
from pages.Login import LoginUI
from pages.Chat import ChatUI
import flet_easy as fs
import flet as ft

#? SpeechRecognition==3.10.0

app = fs.FletEasy(route_init="/chat", route_login="/login")

@app.config
def app_config(page: ft.Page):
    THEME: str | None = page.client_storage.get("THEME") # type: ignore
    if THEME:
        page.theme_mode = THEME # type: ignore
    else:
        THEME = "system"
        page.client_storage.set("THEME", THEME) # type: ignore
        page.theme_mode = THEME # type: ignore


@app.page("/chat", protected_route=True)
def main(data: fs.Datasy) -> ft.View:

    page = data.page
    page.title = "MaseR Assistant"
    # page.theme_mode = ft.ThemeMode.LIGHT
    # page.window_width = 366  #! remove or comment this line when building mobile app (for testing on desktop only)
    # page.window_center()  #! remove or comment this line when building mobile app (for testing on desktop only)
    UI = ChatUI(page)
    return ft.View("/", controls=[UI], appbar=UI.Appbar())


@app.page("/login", True)
def login_page(data: fs.Datasy) -> ft.View:
    page = data.page
    page.title = "Log in"

    return ft.View("login", controls=[LoginUI()])


@app.login
def login(page: ft.Page) -> bool:
    if page.client_storage.get("API") == "123":  # type: ignore
        return True
    return False


app.run(assets_dir="assets")
```

**Comment by NooRMaseR** [comment]
the problem has been solved, thank you
